# Generated by Django 2.0.5 on 2018-06-02 22:46

import apps.webpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(help_text='Ingresar una fotografía de dimensiones no mayor a 1 megapíxel con el nombre sin puntos a excepción de la extensión (Ejemplo: anfitrionas.jpg)', upload_to=apps.webpage.models.upload_gallery)),
                ('desc', models.CharField(help_text='Descripción de la fotografía (Ejemplo: Activación UPN 20/04/2018)', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, to='webpage.Photos'),
        ),
    ]
