# Generated by Django 2.0.5 on 2018-06-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20180603_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='pic', help_text='Nombre de la foto (con el que se guardará en el sistema', max_length=60),
            preserve_default=False,
        ),
    ]
